### ISSUE TITLE
qml module not found

### ISSUE THREAD

**Issue by Alexander-Qi** [Goodman-lab/DP5#52]
Hi, I was running DP5 on WSL-Ubuntu 20.04 LTS. When I tried to launch PyDP4.py, the following error occurred.
```
./PyDP4.py <...> <...>
```
Output:
```
Traceback (most recent call last):
  File "./PyDP4.py", line 39, in <module>
    import Tinker
  File "/home/eugene/workspace/dp5inst/DP5-master/Tinker.py", line 16, in <module>
    import PyDP4
  File "/home/eugene/workspace/dp5inst/DP5-master/PyDP4.py", line 41, in <module>
    import DP5 as DP5
  File "/home/eugene/workspace/dp5inst/DP5-master/DP5.py", line 2, in <module>
    import qml
ModuleNotFoundError: No module named 'qml'
```
How should I fix this problem?

**Comment by ZnS-Eu** [comment]
I have met the same problem before. If you are running it on Ubuntu, maybe you can solve it by installing qml directly.
[http://www.qmlcode.org/installation.html#installing-via-with-intel-compilers](url)
This website tells you how to do it.
