### ISSUE TITLE
Error : NWChem.py, ReadGeometries: No geometry optimisation output

### ISSUE THREAD

**Issue by vas2201** [Goodman-lab/DP5#71]
Dear All, 

I am trying to run PyDP4 on nmrbox, but i am getting following error. Could you please advise, I dont have submit to slurm script , I can run on cpus by default as such. 
I am using tinker and nwchem.

Could you please advise on regarding this error?.

(DP5) spenumutchu@scandium:~/projects/LigandNMR/test1$ ../DP5-master/PyDP4.py -w gmnos ogc CandidateNMR
==========================
PyDP4 script,
integrating Tinker/MacroModel,
Gaussian/NWChem and DP4
v1.0

Copyright (c) 2015-2019 Kristaps Ermanis, Alexander Howarth, Jonathan M. Goodman
Distributed under MIT license
==========================

Settings read from settings.cfg:
  TinkerPath: /home/nmrbox/spenumutchu/projects/LigandNMR/tinker/
  NWChemPath: /home/nmrbox/spenumutchu/anaconda3/envs/DP5/bin/nwchem
['ogc']
CandidateNMR
NMR_path
/home/nmrbox/spenumutchu/projects/LigandNMR/test1/CandidateNMR
Current working directory: /home/nmrbox/spenumutchu/projects/LigandNMR/test1
Initial input files: ['ogc']
NMR file: [PosixPath('/home/nmrbox/spenumutchu/projects/LigandNMR/test1/CandidateNMR')]
Workflow: gmnos

Generating diastereomers...
Generated input files: ['ogc0']

Assuming all computations are done? ...  False
Using preexisting DFT data? ...  False
No conformational search was requested. Skipping...

Setting up geometry optimization calculations...

Running geometry optimization calculations...

Running NWChem DFT geometry optimizations locally...
[]
There were no jobs to run.

Reading DFT optimized geometries...
NWChem.py, ReadGeometries: No geometry optimisation output

**Comment by vas2201** [comment]
Hi there, 
I made some progress, Looks like i did define sterocenters. 
Once i used the following command, I am still getting the follwing error. 

So could you please advise to fix this error ?

(DP5) spenumutchu@scandium:~/projects/LigandNMR/test1$ ../DP5-master/PyDP4.py -w gmoenas ogc NMRdata -t t -d n --nProc 4 -f mmff -c 4
==========================
PyDP4 script,
integrating Tinker/MacroModel,
Gaussian/NWChem and DP4
v1.0

Copyright (c) 2015-2019 Kristaps Ermanis, Alexander Howarth, Jonathan M. Goodman
Distributed under MIT license
==========================


Settings read from settings.cfg:
  TinkerPath: /home/nmrbox/spenumutchu/projects/LigandNMR/tinker/
  NWChemPath: /home/nmrbox/spenumutchu/anaconda3/envs/DP5/bin/nwchem
['ogc']
NMRdata
NMR_path
/home/nmrbox/spenumutchu/projects/LigandNMR/test1/NMRdata
Current working directory: /home/nmrbox/spenumutchu/projects/LigandNMR/test1
Initial input files: ['ogc']
NMR file: [PosixPath('/home/nmrbox/spenumutchu/projects/LigandNMR/test1/NMRdata')]
Workflow: gmoenas
Traceback (most recent call last):
  File "/home/nmrbox/spenumutchu/projects/LigandNMR/test1/../DP5-master/PyDP4.py", line 843, in <module>
    main(settings)
  File "/home/nmrbox/spenumutchu/projects/LigandNMR/test1/../DP5-master/PyDP4.py", line 200, in main
    import StructureInput
  File "/home/nmrbox/spenumutchu/projects/LigandNMR/DP5-master/StructureInput.py", line 4, in <module>
    from InchiGen import *
  File "/home/nmrbox/spenumutchu/projects/LigandNMR/DP5-master/InchiGen.py", line 207
    for l in layers:
                    ^
IndentationError: unindent does not match any outer indentation level
(DP5) spenumutchu@scandium:~/projects/LigandNMR/test1$
